version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dingobot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18t5vyl6kxn7f"
s3_prefix = "dingobot"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
