AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dingobot

  FastAPI on AWS Lambda using AWS SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DingobotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: app.handler
      Runtime: python3.8
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
        NonRoot:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DingobotApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  DingobotFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DingobotFunction.Arn
  DingobotIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DingobotFunction.Arn
